<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>md</string>
		<string>mdown</string>
		<string>markdown</string>
		<string>markdn</string>
	</array>
	<key>hideFromUser</key>
	<true/>
	<key>injectionSelector</key>
	<string>(text.html.markdown)</string>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>Markdown (GitHub)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(^|\G)([`~]{3,}) *(shell|bash|sh)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.raw.syntax.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(^|\G)\2\n?</string>
			<key>name</key>
			<string>markup.raw.block.markdown.shell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.shell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)([`~]{3,}) *(ruby|rb)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.raw.syntax.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(^|\G)\2\n?</string>
			<key>name</key>
			<string>markup.raw.block.markdown.ruby</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)([`~]{3}) *(\w*)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(^|\G)\2\n?</string>
			<key>name</key>
			<string>markup.raw.block.markdown</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.markdown.github</string>
	<key>uuid</key>
	<string>C1028E0A-F9D7-4296-A681-2756A4657AAA</string>
</dict>
</plist>
