<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>hideFromUser</key>
	<true/>
	<key>injectionSelector</key>
	<string>text.html.markdown $, text.html.markdown meta.paragraph.markdown $</string>
	<key>name</key>
	<string>Markdown (GitHub)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(ad[abs])\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.ada</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.ada</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ada</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(antlr|g4)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.antlr</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.antlr</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.antlr</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(applescript|scpt)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.applescript</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.applescript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.applescript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(bib)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>text.bibtex</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.bibtex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.bibtex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(cmake)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.cmake</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.cmake</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cmake</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(dot|gv)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.dot</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.dot</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.dot</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(fish)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.fish</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.fish</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.fish</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(groovy|grt|gtpl|gvy)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.groovy</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.groovy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.groovy</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(hs|haskell)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.haskell</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.haskell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.haskell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(javascript|js|node)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.js</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(java)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.java</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.java</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(json)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.json</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.json</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.json</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(latex|tex)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>text.tex.latex</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.latex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex.latex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(lua)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.lua</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.lua</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(ruby|jruby|macruby|rake|rb|rbx)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.ruby</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.ruby</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(php|inc)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>text.html.php</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.php</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.php</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(py(?:thon)?|rusthon)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.python</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.python</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(css)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.css</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(c\+\+|cpp)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.c++</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.c++</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(c#|csharp)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.cs</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.cs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(c)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.c</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.c</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(html|xhtml)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>text.html.basic</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(shell|sh|bash|zsh)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.shell</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.shell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.shell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(go)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.go</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.go</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.go</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(swift)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.swift</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.swift</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.swift</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3,})\s*(ya?ml)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.language.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.yaml</string>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.yaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.yaml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)\s*([`~]{3})\s*([\w-]*)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.begin.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(^|\G)\s*(\2)\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.strikethrough.markdown.github</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.strikethrough.markdown.github</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.strikethrough.markdown.github</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(~~)([^~]*)(~~)</string>
			<key>name</key>
			<string>markup.other.strikethrough.markdown.github</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown.github</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.link.title.markdown.github</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown.github</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\[)([^\]]*)(\])</string>
			<key>name</key>
			<string>meta.link.reference.markdown.github</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\G)(\|)(?=[^|]+\|)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.table.markdown.github</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;!\|)(^|\G)(?!\|)</string>
			<key>name</key>
			<string>markup.other.table.markdown.github</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>punctuation.definition.table.markdown.github</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.header.markdown.github</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\|)\s*(:?-+:?)\s*(?=\|)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.table.markdown.github</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>text.html.markdown#inline</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\|)\s*(?=\S)((\\\||[^|])+)(?&lt;=\S)\s*(?=\|)</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.markdown.github</string>
	<key>uuid</key>
	<string>C1028E0A-F9D7-4296-A681-2756A4657AAA</string>
</dict>
</plist>
